### ISSUE TITLE
请问是否能够并发回复

### ISSUE THREAD

**Issue by kslr** [ghsxl/Wechat-Autoreply#1]
假设有两个人同时发来了消息，那么点击进去就是两条信息了，能够分别给予回复吗？

**Comment by ghsxl** [comment]
之前玩的时候只是指定回复一个人所以这个没考虑到，应该不行

**Comment by kslr** [comment]
@ghsxl 你好，是这样的，因为我想实现同时有两个人发来信息的话也能够自动回复她们，而现在应该是针对一个人，有什么办法可以实现吗？
